version: "3.7"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/code"
      - /code/node_modules
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true
